server:
  app:
    verbose: true
    debug: true
    host: 0.0.0.0
    port: 5006
    open_browser: false
    force_https: false
    flask_secret_key: "this-app-is-not-secured"
    generate_cache_control_headers: true
    # server_timing_headers: true
    # csp_directives:
    #   script-src:
    #     - browser.sentry-cdn.com
    #   connect-src:
    #     - sentry.prod.si.czi.technology

    # if env == "prod":
    #   api_base_url = f"https://api.cellxgene.cziscience.com/cellxgene/"
    #   web_base_url = f"https://cellxgene.cziscience.com/" # Also used for the multi_dataset index page
    #   data_locator_url = f"https://api.cellxgene.cziscience.com/dp/v1"
    # else:
    #   api_base_url = f"https://api.cellxgene.{env}.single-cell.czi.technology/cellxgene/"
    #   web_base_url = f"https://cellxgene.{env}.single-cell.czi.technology/" # Also used for the multi_dataset index page
    #   data_locator_url = f"https://api.cellxgene.{env}.single-cell.czi.technology/dp/v1"

    # api_base_url: https://${API_DOMAIN}/cellxgene/
    # web_base_url: https://${WEB_DOMAIN}/
  single_dataset:
    datapath: /dataset.h5ad
    var_names: gene_name

  # multi_dataset:
  #   dataroots:
  #     covid19:
  #       base_url: d
  #       dataroot: s3://${CXG_BUCKET_PATH}
  #     corpora_data_portal:
  #       base_url: e
  #       dataroot: s3://${CXG_BUCKET_PATH}

  #   # The index page when in multi-dataset mode:
  #   #   false or null:  this returns a 404 code
  #   #   true:  loads a test index page, which links to the datasets that are available in the dataroot
  #   #   string/URL:  redirect to this URL:  flask.redirect(config.multi_dataset__index)
  #   index: https://${WEB_DOMAIN}/

  # data_locator:
  #   api_base: https://${DATA_LOCATOR_DOMAIN}/dp/v1
  #   # s3 region name.
  #   #   if true, then the s3 location is automatically determined from the datapath or dataroot.
  #   #   if false/null, then do not set.
  #   #   if a string, then use that value (e.g. us-east-1).
  #   s3_region_name: true

  # gene_info:
  #   api_base: https://${DATA_LOCATOR_DOMAIN}/gene_info/v1

  adaptor:
    anndata_adaptor:
      backed: true
  #   cxg_adaptor:
  #     # The key/values under tiledb_ctx will be used to initialize the tiledb Context.
  #     # If 'vfs.s3.region' is not set, then it will automatically use the setting from
  #     # data_locator / s3 / region_name.
  #     tiledb_ctx:
  #       sm.tile_cache_size: 60129542144 # 56 GB
  #       py.init_buffer_bytes: 536870912 # 512MiB

  limits:
    column_request_max: 32
    diffexp_cellcount_max: 10000

dataset:
  presentation:
    max_categories: 1000
    custom_colors: true

  embeddings:
    names: []

  diffexp:
    enable: true
    lfc_cutoff: 0.01
    top_n: 50

  llmembs:
    enable: true
    gene_score_contribution_enable: false
    model_checkpoint: http://cellwhisperer_clip:8910/api
